/** 1. VARIANTS (Record) */
export const ANIMATE_VARIANTS = {
  blink: "hover:animate-blink",
  "blurred-fade-in": "hover:animate-blurred-fade-in",
  "bounce-fade-in": "hover:animate-bounce-fade-in",
  "bounce-horizontal": "hover:animate-bounce-horizontal",
  "bounce-vertical": "hover:animate-bounce-vertical",
  bounceCustom: "hover:animate-bounceCustom", // TODO: check
  "contract-horizontally": "hover:animate-contract-horizontally",
  "contract-vertically": "hover:animate-contract-vertically",
  "expand-horizontally": "hover:animate-expand-horizontally",
  "expand-vertically": "hover:animate-expand-vertically",
  "fade-in": "hover:animate-fade-in",
  "fade-in-down": "hover:animate-fade-in-down",
  "fade-in-left": "hover:animate-fade-in-left",
  "fade-in-right": "hover:animate-fade-in-right",
  "fade-in-up": "hover:animate-fade-in-up",
  "fade-out": "hover:animate-fade-out",
  "fade-out-up": "hover:animate-fade-out-up",
  "fade-out-down-v2": "hover:animate-fade-out-down-v2", // TODO: V2
  "fade-out-left": "hover:animate-fade-out-left",
  "fade-out-right": "hover:animate-fade-out-right",
  flash: "hover:animate-flash",
  flashV0: "hover:animate-flashV0", // TODO
  "flip-horizontal": "hover:animate-flip-horizontal",
  "flip-vertical": "hover:animate-flip-vertical",
  "flip-x": "hover:animate-flip-x",
  "flip-y": "hover:animate-flip-y",
  "flip-in-y": "hover:animate-flip-in-y",
  "flip-in-x": "hover:animate-flip-in-x",
  "flip-out-y": "hover:animate-flip-out-y",
  "flip-out-x": "hover:animate-flip-out-x",
  float: "hover:animate-float",
  hang: "hover:animate-hang",
  heartbeat: "hover:animate-heartbeat",
  "horizontal-vibration": "hover:animate-horizontal-vibration",
  jiggle: "hover:animate-jiggle",
  "jiggle-v0": "hover:animate-jiggle-v0", // TODO
  jump: "hover:animate-jump",
  pop: "hover:animate-pop",
  pulseCustom: "hover:animate-pulseCustom", // TODO: custom
  "pulse-fade-in": "hover:animate-pulse-fade-in",
  rise: "hover:animate-rise",
  "roll-in": "hover:animate-roll-in",
  "roll-out": "hover:animate-roll-out",
  "rotate-180": "hover:animate-rotate-180",
  "rotate-360": "hover:animate-rotate-360",
  "rotate-90": "hover:animate-rotate-90",
  "rotate-in": "hover:animate-rotate-in",
  "rotate-out": "hover:animate-rotate-out",
  "rotational-wave": "hover:animate-rotational-wave",
  "rubber-band": "hover:animate-rubber-band",
  "rubber-band-v0": "hover:animate-rubber-band-v0", // TODO
  scale: "hover:animate-scale", // TODO
  shake: "hover:animate-shake",
  shakeV0: "hover:animate-shakeV0", // TODO
  sink: "hover:animate-sink",
  skew: "hover:animate-skew",
  "slide-down": "hover:animate-slide-down",
  "slide-down-and-fade": "hover:animate-slide-down-and-fade",
  "slide-in-bottom": "hover:animate-slide-in-bottom",
  "slide-in-left": "hover:animate-slide-in-left",
  "slide-in-right": "hover:animate-slide-in-right",
  "slide-in-top": "hover:animate-slide-in-top",
  "slide-left": "hover:animate-slide-left",
  "slide-left-and-fade": "hover:animate-slide-left-and-fade",
  "slide-out-bottom": "hover:animate-slide-out-bottom",
  "slide-out-left": "hover:animate-slide-out-left",
  "slide-out-right": "hover:animate-slide-out-right",
  "slide-out-top": "hover:animate-slide-out-top",
  "slide-right": "hover:animate-slide-right",
  "slide-right-and-fade": "hover:animate-slide-right-and-fade",
  "slide-rotate-in": "hover:animate-slide-rotate-in",
  "slide-rotate-out": "hover:animate-slide-rotate-out",
  "slide-up": "hover:animate-slide-up",
  "slide-up-and-fade": "hover:animate-slide-up-and-fade",
  "slide-up-fade": "hover:animate-slide-up-fade",
  "spin-clockwise": "hover:animate-spin-clockwise",
  "spin-counter-clockwise": "hover:animate-spin-counter-clockwise",
  sway: "hover:animate-sway",
  swing: "hover:animate-swing",
  "swing-drop-in": "hover:animate-swing-drop-in",
  swingV0: "hover:animate-swingV0", // TODO
  squeeze: "hover:animate-squeeze",
  tada: "hover:animate-tada",
  "tilt-horizontal": "hover:animate-tilt-horizontal",
  vibrate: "hover:animate-vibrate",
  wobble: "hover:animate-wobble",
  "zoom-in": "hover:animate-zoom-in",
  "zoom-out": "hover:animate-zoom-out",
  // ----- Default ----- //
  default: "",
};

/** 2. VARIANTS KEYS */
export const ANIMATE_VARIANTS_KEYS = Object.keys(ANIMATE_VARIANTS);
